@echo off
set targetFolder=c:\temp\lego_export

rmdir "%targetFolder%" /q /s
mkdir "%targetFolder%"
copy /y Assembly?.png "%targetFolder%"


rem copy below from openscad console log the copy statements
rem replace  by nothing
rem replace " by "


copy /y ..\Lego_Lib\Plate_2x3.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\Plate_1x2.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\SlopeBrickInverted_2x3.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\SlopeBrickInverted_2x3.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\Plate_2x6.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\MotorCyclePivot.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_brick_1x2.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_brick_1x4.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_brick_1x4.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_pin_without_friction.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_pin_without_friction.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_pin_without_friction.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_pin_without_friction.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\Plate_2x8.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\Plate_2x2.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_shock_absorber_top.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_shock_absorber_bottom.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_shock_absorber_spring.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_shock_absorber_top.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_shock_absorber_bottom.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_shock_absorber_spring.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_axle_6.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_bush.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\Rim_2695.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\Tire_2696.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_plate_toothed_end_1x6.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_plate_toothed_end_1x6.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_bush_toothed.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_bush_toothed.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\Plate_2x3.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\PlateWithPinHoleBothSides_2x2.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_brick_1x6.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_brick_1x6.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_axle_6.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\HingePlate2Fingers.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\HingePlate3Fingers.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\HingePlate2Fingers.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\HingePlate3Fingers.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_bush_toothed.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_bush_toothed.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\Plate_1x4.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\SlopeBrick_3x2.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\Plate_2x2.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\PlateBracket_1x2_1x4.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\PlateRound.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\Plate_1x1.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\Plate_1x1.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\PlateRound.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\Plate_2x2.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\PlateWithHole.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\Plate_1x2.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_plate_toothed_end_1x4.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_brick_1x2.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_brick_1x2.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\PlateBracket_1x2_1x4.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\PlateRound.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\PlateRound.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\Dish.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\PlateRoundWithAxleHole_2x2.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_plate_toothed_end_1x4.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\PlateWithHole.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\SlopeBrick_2x2.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_connector.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_axle_8.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_bush.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_bush.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_connector_toggle_joint_toothed.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_axle_2.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_bush_toothed.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_connector.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_axle_8.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_bush.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_bush.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_connector_toggle_joint_toothed.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_axle_2.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_bush_toothed.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_axle_4.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_bush.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\Rim_2695.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\Tire_2696.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\Tire_2696_Customized.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_axle_4.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_bush_toothed.stl "c:\temp\lego_export"
copy /y ..\Lego_Lib\technic_bush_toothed.stl "c:\temp\lego_export"

pause